# Found Simon's blog about Dependabot for a Python project so started with that.
# https://til.simonwillison.net/github/dependabot-python-setup

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    groups:
    action-dependencies:
      patterns:
      - "*"
    commit-message:
      prefix: "Dependa"

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    python-packages:
      patterns:
      - "*"
    commit-message:
      prefix: "Dependa"
