# My attempt at creating the tbp CI action.
name: Code CI

# Only trigger on the main branch
on:
  # DON"T FORGET TO UNCOMMENT THESE LINE WHEN DONE! 😹😹
  # push:
    # branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab, which is 
  # kind of important for developing this action!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: action/checkout@4
