name: Setup tbp

# Since so many steps need tbp setup, why not try to make that a reusable job?
# It was a pain to find examples of people doing that.
# Getting the runs-on field set is, well, difficult since GitHub actions don't
# support array parameters. Fortunately, Teakowa (https://github.com/Teakowa)
# figured out a work around.
# Discussion: https://github.com/orgs/community/discussions/11692#discussioncomment-3541856
on:
    workflow_call:
      inputs:
        python_version:
          description: The Python version to use. Default="3.12"
          type: string
          required: false
          default: "3.12"
        executes_on:
          description: The operating system. Default= "['ubuntu-latest']"
          type: string
          required: false
          default: "['ubuntu-latest']"


jobs:
    Setup_tbp:
      name: Setup tbp
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: ${{ fromJson(inputs.executes_on) }}
      steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Set up Python ${{inputs.python_version}}
            uses: actions/setup-python@v5
            with:
              python-version: ${{inputs.python_version}}
              cache: 'pip'
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install .[dev]